name: Schedule BI Transfer (staging)

on:
  schedule:
    - cron: "12 5 1 * *"
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
    paths:
      - 'pola-bi/**'
      - '.github/workflows/bi-transfer*.yml'

permissions:
  id-token: write
  contents: read

jobs:
  call-core:
    name: "Run transfer for HEROKU_APP=pola-staging"
    uses: ./.github/workflows/bi-transfer-bigquery.yml
    with:
      heroku_app: "pola-staging"
    secrets: inherit
